# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a7786466db769e1d55c7fb0d43e529e2ccfaef8f766a272ead27adc0f5c5e4b6f37c0a60892c3905791b5b675afd020e688a00b1bb2262b330290b2ebd494ac

test:
  secret_key_base: c7b754059afa2442f3447e70b89b5d0472f72731999573f124ed0a830377dbec82806396931c787587b42c972176075a46cfb972339886cbdcc48c83e1d11162

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
